### PR TITLE
Use addon database to store notes

### PR DESCRIPTION
**Pull request by thani-sh**
Use the addon database to store notes

### CODE REVIEW

**Comment by arunoda** [comment]
This is great.
But, this project is also use to show how to write a Storybook Addon. So, I'd like to keep it simple as possible.

**Comment by thani-sh** [comment]
It'll be difficult to do both on the same repo so I'll create a fork for the production ready version.

**Comment by arunoda** [comment]
Okay. Another Idea. Let's keep the current version in a branch and let's link that for docs when showing about the how to write stories.

Then we can get this in without any issues.

**Comment by thani-sh** [comment]
That's better I guess. Then we could keep the npm module name and no need to start another repo.

**Comment by thani-sh** [comment]
Created a new branch called `version1` for current version

**TODO:**
- [x] Handle database with storybook static build
- [x] Merge this PR https://github.com/kadirahq/storybook-ui/pull/38

**Comment by thani-sh** [comment]
@arunoda this PR is also ready

**Comment by usulpro** [comment]
Is there any doc's about using `addon-db.json` and addon database?

**Comment by thani-sh** [comment]
Hi @UsulPro 
The `addon-db.json` feature was experimental and we temporarily removed it. I'll try to bring it back and add some docs.

**Comment by ndelangen** [comment]
Let's create a PR here: https://github.com/storybooks/storybook

**Pull request closed without merging**
